project_id = "myikezthdiotoddpiwwq"

[functions.detect-gesture]
verify_jwt = false

[functions.create-session]
verify_jwt = false

[functions.log-translation]
verify_jwt = false

[functions.get-session-stats]
verify_jwt = false